name: Buzzer-CI
run-name: Running Buzzer tests.
on: [push, pull_request]
jobs:
  Buzzer-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache 
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Check Buzzer tests
      run: |
           sudo apt update
           sudo apt install clang-14.0
           bazel build //...
           bazel test //...
      env:
       CC:   clang
       CXX:  clang++
